import {
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
  Matches,
  MaxLength,
} from 'class-validator';

export class CreateTransactionDto {
  @IsUUID()
  customerId: string;

  /** Amount as a decimal string — avoids float precision issues.
   *  Format validated here; value (> 0) validated in service. */
  @IsString()
  @IsNotEmpty()
  @Matches(/^\d+(\.\d{1,2})?$/, {
    message: 'amount must be a positive number with at most 2 decimal places',
  })
  amount: string;

  @IsOptional()
  @IsUUID()
  categoryId?: string;

  /** UUID v4 generated by the client — drives idempotency. */
  @IsUUID('4')
  idempotencyKey: string;

  @IsOptional()
  @IsString()
  @MaxLength(500)
  notes?: string;
}
